language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

install:
  - pip install -r requirement.txt

script:
  - docker-compose run --rm app sh -c "python manage.py test && flake8"